name: Flask CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Updated to the latest version compatible with Node.js 20

    - name: Set up Python 3.9
      uses: actions/setup-python@v4  # Updated to the latest version compatible with Node.js 20
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest app.py

    - name: Build Docker Image
      run: |
        docker build -t app .
